version: '3.7'

services:
  dependencies:
    image: jwilder/dockerize
    depends_on:
      - postgres
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_PORT=8080
    volumes:
      - ./:/code
    depends_on:
      - postgres
  postgres:
    build:
      context: docker/postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
      - POSTGRES_DB=postgresDB
    ports:
      - "5432:5432"